default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: m_com_development

test:
  <<: *default
  database: m_com_test

production:
  primary:
    <<: *default
    database: m_com_production
    username: postgres
    password: 123456rgb(187, 50, 4)